name = "garvnanda-profile"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[durable_objects.bindings]]
name = "PROFILE_DO"
class_name = "ProfileState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ProfileState"]

[vars]
PROFILE_URL = "https://github.com/Garvnanda"
